# Generated by Django 5.0.6 on 2024-06-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_cat_basket_product_basket_basketitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.basket",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
