# Generated by Django 5.0.6 on 2024-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productcategory_slug_alter_basket_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Гендер"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Гендер у продукта",
                "verbose_name_plural": "Гендер у продуктов",
                "db_table": "product_gender",
            },
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="gend",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.productgender",
                verbose_name="Гендер для продукта",
            ),
        ),
    ]
